services:
  vectordb:
    container_name: vectordb
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "7432:7432"

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env

volumes:
  vectordb:
