services:

  app:

    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "src/app.py"]
#    depends_on:
#      bot:
#        condition: service_healthy

    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    networks:
      - mynetwork

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    command: ["python", "bot.py"]

    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
