services:

  app:

    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "src/app.py"]

    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      - HF_HOME=/cache/huggingface
      - SENTENCE_TRANSFORMERS_HOME=/cache/sentence_transformers
    volumes:
      - model_cache:/cache  # Подключаем Volume
    networks:
      - mynetwork

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    command: ["python", "bot.py"]
    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  model_cache: