services:

  app:

    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      vectordb:
        condition: service_healthy
      bot:
        condition: service_healthy

    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    networks:
      - mynetwork

  vectordb:
    build:
      context: .
      dockerfile: vectordb.Dockerfile

    env_file:
      - .env
    networks:
      - mynetwork

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile

    env_file:
      - .env
    networks:
      - mynetwork



networks:
  mynetwork:
    driver: bridge

volumes:
  vectordb-data:
