services:

  app:

    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "src/main.py"]

    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    environment:
      - HF_HOME=/cache/huggingface
      - SENTENCE_TRANSFORMERS_HOME=/cache/sentence_transformers
      - TRUST_REMOTE_CODE="true"
      - HF_HUB_OFFLINE=0
      - TRANSFORMERS_OFFLINE=0
      - HF_HUB_DISABLE_SYMLINKS_WARNING=1
    volumes:
      - ./model_cache:/cache
    networks:
      - mynetwork

  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    command: ["python", "bot.py"]
    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  model_cache: